import {BaseRoute} from './base.routes';
import {Observable} from 'rxjs/Observable';
export class ComponentReportsRoute {
    configRoute = function () {
        var baseRouteObj = new BaseRoute();
        return Observable.forkJoin(
            baseRouteObj.importRoute('./app/whatever/Administration/UserListReport/userlist.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Administration/Buildings/admin.buildings.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Administration/Customers/admin.customers.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Administration/Floors/admin.floors.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Administration/Module_wise_Drawings/admin.module_drawings.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Administration/Sites/admin.sites.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Administration/Users/admin.users.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/AsBuilts/Buildings/asbuilts.buildings.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/AsBuilts/Floors/asbuilts.floors.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/AsBuilts/Sites/asbuilts.sites.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/AsBuilts/Drawings/AllDrawings/asbuilts.alldrawings.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/AsBuilts/Drawings/Markups/asbuilts.markups.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/AsBuilts/Drawings/Revisions/asbuilts.revisions.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Space/Floors/space.floors.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Space/Sites/space.sites.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Space/Buildings/space.buildings.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Space/Users/space.users.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Space/GrossAreaDistribution/space.grossareadistribution.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Space/NetAreaDistribution/space.netareadistribution.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Space/GrossAreaReport/space.grossareareport.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Space/SpaceDetails/space.spacedetails.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Space/SpaceFunction/space.spacefunction.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Common/Define Work Type/define-worktype.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Common/SelectPeriod/select.period.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Common/ReportFloorSelection/floorselection.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Space/GrossAreaDistributionTree/space.grossareadistributiontree.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Space/NetAreaDistributionTree/space.netareadistributiontree.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Employees/AllEmployees/employees.allemployees.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Employees/EmployeesNotAssignedSpaces/employees.notassignedspaces.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Employees/AssignedEmployees/employees.assignedemployees.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Employees/AverageSquareFootAnalysis/employees.avgsqfootanalysis.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Employees/CancelledMoves/employees.cancelledmoves.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Employees/ClosedoutMoves/employees.closedoutmoves.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Employees/DetailedOccupancyReports/employees.detailedoccupancy.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Employees/EmployeeMoveDetails/employees.employeemovedetails.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Employees/MovesintheQueue/employees.movesinthequeue.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Employees/NominallyOccupiedSpaces/employees.nominallyoccupiedspaces.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Employees/OccupancyDistributionSpace/employees.spacestandard.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Employees/OverOccupiedSpaces/employees.overoccupiedspaces.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Employees/UnderOccupiedSpaces/employees.underoccupiedspaces.report.route'),
            baseRouteObj.importRoute('./app/whatever/Reports/Space/SpaceDetailsTree/space.spacedetailstree.report.route'),
            baseRouteObj.importRoute('./app/whatever/Reports/Space/GrossAreaReportTree/space.grossareareporttree.report.route'),
            baseRouteObj.importRoute('./app/whatever/Reports/Employees/DetailedOccupancyReportTree/employees.detailedoccupancytree.report.route'),
            baseRouteObj.importRoute('./app/whatever/Reports/Employees/UnderOccupiedSpacesTree/employees.underoccupiedspacestree.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Employees/OverOccupiedSpacesTree/employees.overoccupiedspacestree.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Employees/NominallyOccupiedSpacesTree/employees.nominallyoccupiedspacestree.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Employees/OccupancyDistributionSpaceTree/employees.spacestandardtree.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Employees/AssignedEmployeesTree/employees.assignedemployeestree.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Employees/AverageSquareFootAnalysisTree/employees.avgsqfootanalysistree.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Common/SelectOrgUnitForReport/select.orgunit.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/WorkOrder/EquipmentWorkHistory/wo.workhistory.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/WorkOrder/ServiceRequestFeedback/wo.servicereqfeedback.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/WorkOrder/PM/PMWorkFlowHistory/wo.pmworkflowhistory.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/WorkOrder/PM/PMCompletedWorkFlowHistory/wo.pmcompletedworkflowhistory.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Space/GrossAreaOrgDistribution/space.grossareaorgdistribution.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Space/GrossAreaOrgDistributionTree/space.grossareaorgdistributiontree.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/WorkOrder/SR/SRWorkFlowHistory/wo.srworkflowhistory.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/WorkOrder/SR/SRCompletedWorkFlowHistory/wo.srcompletedworkflowhistory.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Assets/AssetClassList/asset.classlist.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Assets/AssetListByFloor/asset.listbyfloor.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Assets/AssetDetails/asset.details.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Assets/AssetListbyClass/asset.listbyclass.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/WorkOrder/PM/MonthlyPMSummary/wo.monthlypmsummary.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/RealProperty/Critical Dates/realProperty.critical-dates.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/RealProperty/Lease summary/realProperty.lease-summary.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/RealProperty/Current leases/realProperty.current-leases.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/RealProperty/Leased Spaces/realProperty.leased-spaces.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/RealProperty/Cost Obligation/realProperty.cost-obligation.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/RealProperty/Facilities Summary/realProperty.facilities-summary.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/RealProperty/RenewinginNextYear/renewingiNextYear-route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/RealProperty/LeaseServiceClauses/leaseServiceClauses-report-route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/RealProperty/Buildings by Condition/realProperty.buildings-by-condition.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/RealProperty/Buildings by Year/realProperty.buildings-by-year.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/RealProperty/Building Area by Year/realProperty.building-area-by-year.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/RealProperty/RenovationDetails/renovation-details-route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/RealProperty/ProjectionforanYear/projectionFoanYear-route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/CustomReports/customreports.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/RealProperty/Rent Rolls/realProperty.rent-rolls.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Scheduling/RoomBookingRequestDetails/scheduling.roombookreqdetails.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Scheduling/RoomBookingRequestDetailsByUser/scheduling.roombookreqdetailsbyuser.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Scheduling/RoomBookingSummaryDetails/scheduling.roombooksummarydetails.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Scheduling/SeatBookingRequestdetails/scheduling.seatbookreqdetails.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Furniture/FurnitureClassList/furniture.classlist.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Furniture/FurnitureListByFloor/furniture.listbyfloor.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Furniture/FurnitureDetails/furniture.details.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Furniture/FurnitureListbyClass/furniture.listbyclass.report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Space/NetAreaOrganizationalDistributionTree/space.net-area-organizational-distribution-tree-report.route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Space/SpaceOccupancy/space-occupancy-report-route'),
            baseRouteObj.importRoute('./app/whatever/reports/workorder/sr/srstausbasedreports/wo.srstatusbasedreports.route'),
            baseRouteObj.importRoute('./app/whatever/reports/scheduling/userreservation/scheduling.userreservationdetails.report.route'),
            baseRouteObj.importRoute('./app/whatever/reports/scheduling/cancelledreservation/scheduling.cancelledreservationdetails.report.route'),
            baseRouteObj.importRoute('./app/whatever/reports/workorder/sr/sractionpointstatus/wo.sractionpointstatusreports.route'),
            baseRouteObj.importRoute('./app/whatever/reports/workorder/pm/statusbased/wo.pmstatusbased.report.route'),
            baseRouteObj.importRoute('./app/whatever/reports/documents/documentdetails/documents.details.report.route'),
            baseRouteObj.importRoute('./app/whatever/reports/workorder/pm/dailyreport/wo.pmdaily.report.route'),
            baseRouteObj.importRoute('./app/whatever/reports/workorder/sr/dailyreport/wo.srdaily.report.route'),
            baseRouteObj.importRoute('./app/whatever/reports/workorder/sr/weeklyreport/wo.srweekly.report.route'),
            baseRouteObj.importRoute('./app/whatever/reports/workorder/pm/weeklyreport/wo.pmweekly.report.route'),
            baseRouteObj.importRoute('./app/whatever/reports/workorder/pm/monthlyreportclosed/wo.pmmonthlyclosed.report.route'),
            baseRouteObj.importRoute('./app/whatever/reports/workorder/pm/monthlyreportopen/wo.pmmonthlyopen.report.route'),
            baseRouteObj.importRoute('./app/whatever/reports/workorder/sr/monthlyreportclosed/wo.srmonthlyclosed.report.route'),
            baseRouteObj.importRoute('./app/whatever/reports/workorder/sr/monthlyreportopen/wo.srmonthlyopen.report.route'),
            baseRouteObj.importRoute('./app/whatever/reports/workorder/pm/delayedworkorders/delayedworkorders.report.route'),
            baseRouteObj.importRoute('./app/whatever/reports/workorder/sr/numberrange/wo.srnumberrange.report.route'),
            baseRouteObj.importRoute('./app/whatever/reports/workorder/sr/daterange/wo.srdaterange.report.route'),
            baseRouteObj.importRoute('./app/whatever/reports/workorder/sr/delayedworkorders/delayedworkorders.report.route'),
            baseRouteObj.importRoute('./app/whatever/reports/workorder/pm/daterange/wo.pmdaterange.report.route'),
            baseRouteObj.importRoute('./app/whatever/reports/workorder/pm/numberrange/wo.pmnumberrange.report.route'),
            baseRouteObj.importRoute('./app/whatever/reports/workorder/pm/scheduledfortoday/wo.pmscheduledfortoday.route'),
            baseRouteObj.importRoute('./app/whatever/reports/workorder/sr/scheduledfortoday/wo.srscheduledfortoday.route'),
            baseRouteObj.importRoute('./app/whatever/reports/workorder/pm/productivitybytechnician/wo.pmproductivity.route'),
            baseRouteObj.importRoute('./app/whatever/reports/workorder/sr/productivitybytechnician/wo.srproductivity.route'),
            baseRouteObj.importRoute('./app/whatever/reports/workorder/pm/costdetails/wo.pmwocostdetails.report.route'),
            baseRouteObj.importRoute('./app/whatever/reports/workorder/sr/costdetails/wo.srwocostdetails.report.route'),
            baseRouteObj.importRoute('./app/whatever/reports/workorder/sr/PrintServiceRequest/PrintServiceRequest_Report.route'),
            baseRouteObj.importRoute('./app/whatever/Reports/scheduling/alluserreservationdata/scheduling.alluserreservationdata.report.route'),
            baseRouteObj.importRoute('./app/whatever/Reports/scheduling/equipment reservation/scheduling.equipmentreservationdata.report.route'),
            baseRouteObj.importRoute('./app/whatever/Reports/Telecom/TelecomListByFloor/telecom.listbyfloor.report.route'),
            baseRouteObj.importRoute('./app/whatever/Reports/Telecom/ObjectClassList/object.classlist.report.route'),
            baseRouteObj.importRoute('./app/whatever/Reports/Telecom/ObjectDetails/object.details.report.route'),
            baseRouteObj.importRoute('./app/whatever/Reports/Telecom/ObjectListbyClass/object.listbyclass.report.route'),
            baseRouteObj.importRoute('./app/whatever/Reports/Electrical/ComponentTypeList/component.typelist.report.route'),
            baseRouteObj.importRoute('./app/whatever/Reports/Electrical/ComponentListByFloor/component.listbyfloor.report.route'),
            baseRouteObj.importRoute('./app/whatever/Reports/Electrical/ComponentDetails/component.details.report.route'),
            baseRouteObj.importRoute('./app/whatever/Reports/Electrical/ComponentListbyType/component.listbytype.report.route'),
            baseRouteObj.importRoute('./app/whatever/Reports/FireandSafety/ComponentTypeList/component.typelist.report.route'),
            baseRouteObj.importRoute('./app/whatever/Reports/FireandSafety/ComponentListByFloor/component.listbyfloor.report.route'),
            baseRouteObj.importRoute('./app/whatever/Reports/FireandSafety/ComponentDetails/component.details.report.route'),
            baseRouteObj.importRoute('./app/whatever/Reports/FireandSafety/ComponentListbyType/component.listbytype.report.route'),
            baseRouteObj.importRoute('./app/whatever/Reports/Mechanical/ComponentTypeList/component.typelist.report.route'),
            baseRouteObj.importRoute('./app/whatever/Reports/Mechanical/ComponentListByFloor/component.listbyfloor.report.route'),
            baseRouteObj.importRoute('./app/whatever/Reports/Mechanical/ComponentDetails/component.details.report.route'),
            baseRouteObj.importRoute('./app/whatever/Reports/Mechanical/ComponentListbyType/component.listbytype.report.route'),
            baseRouteObj.importRoute('./app/whatever/Reports/CAI/SpaceDriverTree/spaceDriverTree.report.route'),
            baseRouteObj.importRoute('./app/whatever/Reports/CAI/BuildingStatus/building-status-route'),
            baseRouteObj.importRoute('./app/Whatever/Reports/Space/AdditionalReports/reports-route'),
            baseRouteObj.importRoute('./app/whatever/Reports/WorkOrder/Maintenance/ProceduresandSteps/wo.proceduresandsteps.route'),
            baseRouteObj.importRoute('./app/whatever/Reports/WorkOrder/Maintenance/SchedulesbyEquipment/wo.schedulesbyequipment.route'),
            baseRouteObj.importRoute('./app/whatever/Reports/WorkOrder/Maintenance/SchedulesbyDateRange/wo.schedulesbydaterange.route')
        );
    }
}